/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        app: "rgb(var(--color-app) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        "surface-raised": "rgb(var(--color-surface-raised) / <alpha-value>)",
        "surface-muted": "rgb(var(--color-surface-muted) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        "border-muted": "rgb(var(--color-border-muted) / <alpha-value>)",
        "border-strong": "rgb(var(--color-border-strong) / <alpha-value>)",
        divider: "rgb(var(--color-divider) / <alpha-value>)",
        "divider-strong": "rgb(var(--color-divider-strong) / <alpha-value>)",
        foreground: "rgb(var(--color-foreground) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        subtle: "rgb(var(--color-subtle) / <alpha-value>)",
        inverse: "rgb(var(--color-inverse) / <alpha-value>)",
        sidebar: "rgb(var(--color-sidebar) / <alpha-value>)",
        "sidebar-foreground":
          "rgb(var(--color-sidebar-foreground) / <alpha-value>)",
        "sidebar-muted": "rgb(var(--color-sidebar-muted) / <alpha-value>)",
        "sidebar-border": "rgb(var(--color-sidebar-border) / <alpha-value>)",
        "sidebar-accent": "rgb(var(--color-sidebar-accent) / <alpha-value>)",
        "sidebar-accent-soft":
          "rgb(var(--color-sidebar-accent-soft) / <alpha-value>)",
        "sidebar-accent-contrast":
          "rgb(var(--color-sidebar-accent-contrast) / <alpha-value>)",
        primary: "rgb(var(--color-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--color-primary-hover) / <alpha-value>)",
        "primary-soft": "rgb(var(--color-primary-soft) / <alpha-value>)",
        "primary-border": "rgb(var(--color-primary-border) / <alpha-value>)",
        "primary-text": "rgb(var(--color-primary-text) / <alpha-value>)",
        "primary-contrast":
          "rgb(var(--color-primary-contrast) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-soft": "rgb(var(--color-accent-soft) / <alpha-value>)",
        "accent-border": "rgb(var(--color-accent-border) / <alpha-value>)",
        "accent-text": "rgb(var(--color-accent-text) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        "success-soft": "rgb(var(--color-success-soft) / <alpha-value>)",
        "success-border": "rgb(var(--color-success-border) / <alpha-value>)",
        "success-text": "rgb(var(--color-success-text) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        "warning-soft": "rgb(var(--color-warning-soft) / <alpha-value>)",
        "warning-border": "rgb(var(--color-warning-border) / <alpha-value>)",
        "warning-text": "rgb(var(--color-warning-text) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        "danger-soft": "rgb(var(--color-danger-soft) / <alpha-value>)",
        "danger-border": "rgb(var(--color-danger-border) / <alpha-value>)",
        "danger-text": "rgb(var(--color-danger-text) / <alpha-value>)",
        skeleton: "rgb(var(--color-skeleton) / <alpha-value>)",
        "score-high": "rgb(var(--color-score-high) / <alpha-value>)",
        "score-mid": "rgb(var(--color-score-mid) / <alpha-value>)",
        "score-low": "rgb(var(--color-score-low) / <alpha-value>)",
        "score-poor": "rgb(var(--color-score-poor) / <alpha-value>)",
        "score-empty": "rgb(var(--color-score-empty) / <alpha-value>)",
        "chart-grid": "rgb(var(--color-chart-grid) / <alpha-value>)",
        "chart-cursor": "rgb(var(--color-chart-cursor) / <alpha-value>)",
      },
      fontFamily: {
        rubik: ["Rubik", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
      },
    },
  },
  plugins: [],
};
